POST https://fullstackopen-backend-ztmk.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number": "1"
}
###
GET https://fullstackopen-backend-ztmk.onrender.com/api/persons